export type CanonicalId = string & { readonly __brand: "CanonicalId" };

export enum LifecycleGate {
  G0_AREA_AOI = "G0_AREA_AOI",
  G1_PROSPECT = "G1_PROSPECT",
  G2_TARGET_GENERATED = "G2_TARGET_GENERATED",
  G3_FIELD_VALIDATED = "G3_FIELD_VALIDATED",
  G4_GEO_SUPPORTED = "G4_GEO_SUPPORTED",
  G5_DRILL_READY = "G5_DRILL_READY",
  G6_DISCOVERY = "G6_DISCOVERY",
  G7_RESOURCE_DEFINITION = "G7_RESOURCE_DEFINITION",
  G8_RESOURCE_GROWTH = "G8_RESOURCE_GROWTH",
  G9_STUDY_FEASIBILITY = "G9_STUDY_FEASIBILITY",
  G10_DEVELOPMENT = "G10_DEVELOPMENT",
}

export enum OperationalState {
  AOI_READY = "AOI_READY",
  TARGET_GENERATION_ONLY = "TARGET_GENERATION_ONLY",
  HUMAN_REVIEW_REQUIRED = "HUMAN_REVIEW_REQUIRED",
  NORMAL_PROCESSING = "NORMAL_PROCESSING",
}

export enum DecisionState {
  CREATED = "CREATED",
  EVIDENCE_REQUESTED = "EVIDENCE_REQUESTED",
  EVIDENCE_RECEIVED = "EVIDENCE_RECEIVED",
  EVIDENCE_ASSESSMENT = "EVIDENCE_ASSESSMENT",
  EVIDENCE_REQUIRED = "EVIDENCE_REQUIRED",
  CONFLICT_RESOLUTION_REQUIRED = "CONFLICT_RESOLUTION_REQUIRED",
  CAPITAL_INPUT_REQUIRED = "CAPITAL_INPUT_REQUIRED",
  PARTNER_APPROVAL_REQUIRED = "PARTNER_APPROVAL_REQUIRED",
  DECISION_READY = "DECISION_READY",
  HUMAN_REVIEW_REQUIRED = "HUMAN_REVIEW_REQUIRED",
  CONDITIONALLY_APPROVED = "CONDITIONALLY_APPROVED",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  EXECUTION_AUTHORISED = "EXECUTION_AUTHORISED",
  EXECUTION_IN_PROGRESS = "EXECUTION_IN_PROGRESS",
  OUTCOME_PENDING = "OUTCOME_PENDING",
  OUTCOME_CAPTURED = "OUTCOME_CAPTURED",
  PORTFOLIO_REASSESSMENT = "PORTFOLIO_REASSESSMENT",
  CLOSED = "CLOSED",
  REOPENED = "REOPENED",
}

export enum EvidenceFitness {
  NOT_ASSESSED = "NOT_ASSESSED",
  VALIDATED = "VALIDATED",
  DECISION_GRADE = "DECISION_GRADE",
  QUALIFIED_WITH_LIMITATIONS = "QUALIFIED_WITH_LIMITATIONS",
  NOT_FIT = "NOT_FIT",
  SUPERSEDED = "SUPERSEDED",
}

export enum SecurityClassification {
  C0_PUBLIC = "C0_PUBLIC",
  C1_INTERNAL = "C1_INTERNAL",
  C2_CONFIDENTIAL_TECHNICAL = "C2_CONFIDENTIAL_TECHNICAL",
  C3_COMMERCIAL_JV_RESTRICTED = "C3_COMMERCIAL_JV_RESTRICTED",
  C4_CONTROLLED_DISCLOSURE = "C4_CONTROLLED_DISCLOSURE",
}

export interface ActorContext {
  tenantId: string;
  userId: string;
  roleAssignmentId: string;
  correlationId: string;
}
